### ISSUE TITLE
What program did you use to view the slides?

### ISSUE THREAD

**Issue by btakita** [Gabriella439/slides#7]
I tried using https://mark.show/https://raw.githubusercontent.com/Gabriel439/slides/master/dhall-intro/dhall-intro.md#, but mark.show uses the `---` (`<hr>`; used by reveal.js) to create a slide.

What program did you use to view the slides?

**Comment by Gabriella439** [comment]
I use `pandoc` to generate slides, like this:

```
 pandoc -s -t slidy -o dhall-intro.html dhall-intro.md
```

**Comment by btakita** [comment]
Thank you

**Comment by btakita** [comment]
In case anybody wants to views these slides online, I created a gist to view them using mark.show.

https://mark.show/https://gist.githubusercontent.com/btakita/5e8f4b66b100c3bc5f7fba5ed28e3e98/raw/dhall-intro.md
