### ISSUE TITLE
Using dhall for governance

### ISSUE THREAD

**Issue by btakita** [Gabriella439/slides#8]
Thank you @Gabriel439 for the talk. I'm interested in how Dhall is being used for governance. Are you able to disclose what organization is using Dhall for their governance? Is there a sample org doc or contract? This could be a "killer app".

https://youtu.be/ikEx56F6g1M?t=6249

**Comment by Gabriella439** [comment]
I was referring to this: https://twitter.com/buchmanster/status/1343743673817829377

**Comment by btakita** [comment]
Thank you again!

**Comment by Gabriella439** [comment]
You're welcome! 🙂
