### ISSUE TITLE
Can you add a license to the code in the regex slides? 🙏

### ISSUE THREAD

**Issue by pchiusano** [Gabriella439/slides#9]
Like at the end, a note "all code in these slides is hereby MIT licensed, text below" or something... I can do a PR if you like. We're thinking of adapting it for regex support in Unison, where we want something simple and performant.

Also thanks for writing and sharing the slides! It was fun reading.

**Comment by Gabriella439** [comment]
You're welcome!

You can find the license here: https://github.com/Gabriel439/slides/issues/9

**Comment by pchiusano** [comment]
Thanks so much!
